export interface ICargue {
  idCargue:string,
  nombreArchivo:string,
  tipoArchivo:string,
  tipoEntidad:string,
  entidad:string,
  codigoEntidad:string,
  secuencia:string,
  fecCargue:string,
  usuario:string,
  numeroControl:string,
  resultado:string,
  nombre:string,
  fecModificacion:string,
  esDefinitiva:string,
  idUsuario:string,
  idOrganizacion:string
  estado:string,
  monto:string,
  nroCuentas:string,
  saldoInicial:string,
  remuneracion:string,
  causalRechazo:string,
  observacionesRechazo:string,
  vbnotesoreria: number,
  vbnocontador:number
}
