export interface IConsolidado {
    CodigoValor:string,
    Nombre:string,
    IdCargue:string,
    CargueNombre:string,
    FechaCargue:Date,
    NroCuentas:string,
    Monto:string,
    TasaPonderada:string,
    Remuneracion:string,
    Estado:string,
    TipoArchivo:string,
    FechaTraslado:Date,
    FechaCorte:Date,
    TotalRemuneracionAcumulada:string,
    TotalSaldoInicial:string,
}