export interface Iimpresionpdf{
    consecutivo: number,
    fechaInicio: Date,
    fechaCargue: Date,
    nombreInstitucion: string,
    valor: number,
    valorTotal: number,
    nombreArchivo: string,
    numeroCuenta: number,
    fechaTransmision: Date,
    tasaPonderada: number,
    observacion: string,
    cuentaCudDestino: number,
    portafolioDestino: number,
}